### ISSUE TITLE
MacOS icon

### ISSUE THREAD

**Issue by zkvvoob** [seird/gotify-tray#12]
Hello there,

Love the app and would like to keep using it on my Macbook. 

Would you consider updating the icon for the MacOS version so that it matches the general OS design language? Here's a suggestion that you are free to use if you like.

<img width="512" alt="icon_1024x1024" src="https://user-images.githubusercontent.com/7645808/192091110-f0c4eca3-5a87-4457-8b9c-a3598edda1f7.png">

Thanks and keep up the good work!

**Comment by seird** [comment]
Thanks for the suggestion. Do these images look good to you? For the tray icon, I think the one without the white box looks a bit more legible, but it's less consistent.

![logo](https://user-images.githubusercontent.com/55763130/192101280-f645807a-d0fb-4d16-8bf1-fa47719cdd2d.png)


![1664027633_1907](https://user-images.githubusercontent.com/55763130/192101715-0e14689b-668a-4e10-910f-fb674c324a60.png)

![tray-1](https://user-images.githubusercontent.com/55763130/192101283-494e0d00-f248-4448-8139-0125acb090de.png)

![tray-2](https://user-images.githubusercontent.com/55763130/192101290-ab54d6b4-3375-4197-b507-b4904c5f4122.png)

Any further ideas are always welcome

**Comment by zkvvoob** [comment]
The app icon looks great to me. As for the menu bar icon, you are right - the white background is unnecessary. However, if you ask me, I'd say we go for something even more simplified.

Here are two suggestions (though I'm not sure how they'd look exactly) - one dark to go with the OS light more and another one with just outlines - for dark modes.

![gotify_light](https://user-images.githubusercontent.com/7645808/192106749-3ddf1c6c-fb6a-452a-b79c-830819ba0dfe.png)

![gotify_dark](https://user-images.githubusercontent.com/7645808/192106751-95cc43b2-6f5c-4813-8196-72efbddd0578.png)

Or maybe just something with white oulines:
![gotify_dark2](https://user-images.githubusercontent.com/7645808/192106898-95cdedcd-6129-418f-8e78-3f447a70b028.png)

**Comment by seird** [comment]
The monochrome icons are a good idea. The outlines will probably have to be a bit thicker though:

![line-dark](https://user-images.githubusercontent.com/55763130/192133684-dee9c8f1-0d35-481c-b9eb-50734ac95bd7.png)
![line-light](https://user-images.githubusercontent.com/55763130/192133680-73ee03a7-2cff-40f9-bbf3-8c1223c64631.png)
![light](https://user-images.githubusercontent.com/55763130/192133682-d50d97e4-e4f6-42dd-8cca-21f95c7d43e4.png)


In any case, adding system theme based icons will require some extra work (not specific to macos), so for now I'll keep the colored icons and add it to my to do list.

**Comment by zkvvoob** [comment]
Brilliant! Can't wait to see the new release.

Thanks, @seird!
