### ISSUE TITLE
Client cannot handle images

### ISSUE THREAD

**Issue by Tin-Joy59** [seird/gotify-tray#21]
Hello and thank you for creating this app. I'm very happy with it!

I noticed that images aren't parsed correctly in the text are inside the app. I have Jellyfin connected to Gotify and it sends notifications with the cover image of movies and episodes when they are added/removed or watched. The webhook plugin uses Markdown syntax to pass images that are then displayed correctly in the Gotify WebUI. The same cannot be said for this app. I'm attaching images for clarity. 

Gotify Tray cannot parse the image and url correctly.
![image](https://user-images.githubusercontent.com/86809766/204162559-e505e4a5-a894-4a75-9f18-b318f560667b.png)

Correctly displayed in the web ui.
![image](https://user-images.githubusercontent.com/86809766/204162564-01ef6f60-dc6d-42d9-8a3f-d9813d05e93f.png)

**Comment by seird** [comment]
Hi, thank you for trying out the app!

> I noticed that images aren't parsed correctly in the text are inside the app.

A known limitation of the Qt markdown parser is that it cannot render external resources. I haven't found a good solution for this problem yet, other than just displaying the messages in a webview. As "temporary" workaround I added an option to enable image popups when hovering over a URL with an image extension (settings->advanced).

What I can do, is parse the message and look for an image . So for any message in the format
- `![](https://example.com/image.jpg)`
- or, `https://example.com/image.jpg`
without any other contents, the image will be downloaded and displayed (skipping the markdown renderer).

I'll push an update in a bit which you can try if you want.

**Comment by Tin-Joy59** [comment]
Awesome, I'll report on it. Thanks!

**Comment by seird** [comment]
added basic image rendering in the [render-images](/seird/gotify-tray/tree/render-images) branch, or you can download the [build artifact](https://github.com/seird/gotify-tray/actions?query=branch%3Arender-images++) for windows at the bottom of the page.

Seems to work fine for me, but there are definitely some performance improvements that can be made.

Note that it still only works for messages that don't have any extra text aside from the (markdown) image link.

**Comment by Tin-Joy59** [comment]
I tried it out and it works just as described! Thank you very much for the addition!
