### ISSUE TITLE
Bug: automatically exit when there are a large number of messages

### ISSUE THREAD

**Issue by spysir** [seird/gotify-tray#27]
version: gotify-tray-installer-win.exe 0.4.1
The software will automatically exit from the tray when there are a lot of messages

**Comment by seird** [comment]
how many messages are we talking about? I'm able to spam new messages non-stop.
When the crash happens, are you interacting with the main window of the application (e.g. dragging the window around)?

**Comment by spysir** [comment]
> how many messages are we talking about? I'm able to spam new messages non-stop. When the crash happens, are you interacting with the main window of the application (e.g. dragging the window around)?

There are like 20 messages sent at the same time, I don't interact with the main window

**Comment by spysir** [comment]
> how many messages are we talking about? I'm able to spam new messages non-stop. When the crash happens, are you interacting with the main window of the application (e.g. dragging the window around)?

My service is ' rss→email→gotify '
When rss is updated, gotify will receive a large number of notifications, at this time gotify-tray will crash and automatically exit

**Comment by seird** [comment]
can you confirm if the crash also occurs in [version 0.3.1](https://github.com/seird/gotify-tray/releases/tag/0.3.1)?

**Comment by spysir** [comment]
> can you confirm if the crash also occurs in [version 0.3.1](https://github.com/seird/gotify-tray/releases/tag/0.3.1)?

Version 0.3.1 I have not tried

**Comment by seird** [comment]
I added some relevant logging if you want to give it a try: https://github.com/seird/gotify-tray/actions/runs/4336127164 has a windows installer in the build artifacts

Logging has to be enabled first (set settings->advanced->level to ERROR or lower)

**Comment by spysir** [comment]
> I added some relevant logging if you want to give it a try: https://github.com/seird/gotify-tray/actions/runs/4336127164 has a windows installer in the build artifacts
> 
> Logging has to be enabled first (set settings->advanced->level to ERROR or lower)

I tried it a few times and it worked without crashing ！Thank you

**Comment by seird** [comment]
that's great, but I would still like to know what exactly caused the issue. In any case, the culprit won't be the number of messages arriving at a given time, but rather the content / parsing of the message.

so it would be useful if you could still check the logs
