### ISSUE TITLE
Releasing updates to PyPi.org

### ISSUE THREAD

**Issue by marvin8** [seird/gotify-tray#3]
Thanks for creating and maintaining gotify-tray. I used it constantly.

I've installed gotify-tray with pipx on my system. Pipx gets apps from PyPi.org by default and it found version 0.1.10 on there.

You're previous and also your latest update don't seem to have made it to PyPi.org.

I am now wondering, are you intending to release future updates on PyPi.org as well?

**Comment by seird** [comment]
just pushed the updates to pypi, thanks for the reminder!

**Comment by marvin8** [comment]
Thanks for that... much appreciated.

If you are interested in automatically deploying new releases to PyPi.org with Github Actions, here's a short list of examples I found (in no particular order):

- [Automating PyPI releases with Github Actions](https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/)
- [PyPI Deployment](https://github.com/marketplace/actions/pypi-deployment)
- [pypi-publish](https://github.com/marketplace/actions/pypi-publish)

I haven't used any of these myself, so I can't provide any feedback on these... sorry.
