### ISSUE TITLE
request support markdown

### ISSUE THREAD

**Issue by spysir** [seird/gotify-tray#8]
It's a great project, but it's a pity it doesn't support markdown

**Comment by seird** [comment]
Hi,

the notification pop-ups do not support markdown on any platform as far as I know. To achieve this a custom notification would have to be created (maybe as an optional alternative), bypassing the native notification center.


In the main window however, there is some basic markdown rendering. To enable it, you need to set the contentType to "text/markdown" when pushing a message ([docs](https://gotify.net/docs/msgextras#clientdisplay)):

```json
{
  "extras": {
    "client::display": {
      "contentType": "text/markdown"
    }
  }
}
```

It's not much though (images aren't rendered):

![markdown](https://user-images.githubusercontent.com/55763130/187064029-ee0950e0-428f-45bc-8d4f-78387c2968f8.png)
